version: '3.3'
#http://192.168.99.100:8123/ wegen Toolbox

services:
  webserver:
    build: docker/php
    restart: always
    ports:
      - '9000:80'
    volumes:
      - ./code:/var/www/html
      - ./fonts:/usr/share/fonts/truetype/custom
    networks:
      - sharepicgenerator
  grunt:
    build: docker/node
    restart: always
    volumes:
      - ./code:/var/www/html
    command: grunt
    working_dir: /var/www/html
    networks:
      - sharepicgenerator
networks:
  sharepicgenerator: