version: '3.3'

services:
  webserver:
    build: docker/php
    ports:
      - '${PORT}:80'
    volumes:
      - ./code:/var/www/html
      - ./fonts:/usr/share/fonts/truetype/custom
      - ./deployment/scripts:/root/scripts
    networks:
      - sharepicgenerator
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - sharepicgenerator
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: "no"
    networks:
      - sharepicgenerator
    volumes:
      -  ./code/dist/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  node:
    build: docker/node
    volumes:
      - ./code:/var/www/html
    command: npm run watch
    working_dir: /var/www/html
    networks:
      - sharepicgenerator
  mkdocs:
    build: docker/mkdocs
    ports:
      - '9001:8080'
    volumes:
      - ./mkdocs:/mkdocs
      - ./code:/code

  selenium-hub:
    image: selenium/hub:3.141.59-gold
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - sharepicgenerator
  chrome:
    image: selenium/node-chrome:3.141.59-20200409
    volumes:
      - ./tests:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - sharepicgenerator
networks:
  sharepicgenerator:
volumes:
  db_data: {}