version: '3.3'
#http://192.168.99.100:9000/ wegen Toolbox

services:
  webserver:
    build: docker/php
    ports:
      - '${PORT}:80'
    volumes:
      - ./code:/var/www/html
      - ./fonts:/usr/share/fonts/truetype/custom
      - ./deployment/sshkeys:/root/.ssh
      - ./deployment/scripts:/root/scripts
    networks:
      - sharepicgenerator
  node:
    build: docker/node
    volumes:
      - ./code:/var/www/html
    command: npm run watch
    working_dir: /var/www/html
    networks:
      - sharepicgenerator
  mkdocs:
    build: docker/mkdocs
    ports:
      - '9001:8080'
    volumes:
      - ./mkdocs:/mkdocs
      - ./code/dist/documentation:/mkdocs/site
networks:
  sharepicgenerator: