version: '3.3'
#http://192.168.99.100:9000/ wegen Toolbox

services:
  webserver:
    build: docker/php
    ports:
      - '${PORT}:80'
    volumes:
      - ./code:/var/www/html
      - ./fonts:/usr/share/fonts/truetype/custom
      - ./deployment/sshkeys:/root/.ssh
      - ./deployment/scripts:/root/scripts
    networks:
      - sharepicgenerator
  node:
    build: docker/node
    volumes:
      - ./code:/var/www/html
    command: npm run watch
    working_dir: /var/www/html
    networks:
      - sharepicgenerator
  mkdocs:
    build: docker/mkdocs
    ports:
      - '9001:8080'
    volumes:
      - ./mkdocs:/mkdocs
      - ./code:/code

  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-20200409
    volumes:
      - ./tests:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  python:
    build: docker/python
    volumes:
      - ./tests:/tests
    networks:
      - sharepicgenerator
networks:
  sharepicgenerator: