name: Deployment

on:
  push:
    branches: [ test ]

jobs:
  postdeploy-test:
    runs-on: ubuntu-latest
    container:
      image: node:13.6
      options: --network-alias testHost
    env:
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Webdriver
        run: |
          cd tests
          npm install selenium-webdriver
          ls -l

      - name: Run test
        run: |
          pwd
          cd tests
          pwd
          SELENIUM_REMOTE_URL="testHost/wd/hub" node test.js
