name: Deployment

on:
  push:
    branches: [ test ]

jobs:
  postdeploy-test:
    runs-on: ubuntu-latest
    container:
      image: node:13.6
      options: --network-alias testHost
    env:
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      chrome:
        image: selenium/node-chrome:3.141.59-20200409
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - uses: actions/checkout@v2

      - name: Install Webdriver
        run: |
          npm install selenium-webdriver

      - name: Run test
        run: |
          cd tests
          SELENIUM_REMOTE_URL="http://testHost:4444/wd/hub" node test.js
