name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Save version
        run: |
          echo $GITHUB_SHA > code/dist/version.txt
          TZ='Europe/Berlin' date >> code/dist/version.txt


      - name: see version
        run: |
          cat code/dist/version.txt

      - uses: actions/cache@v3
        id: cache-dist
        with:
          path: ~/code/dist
          key: ${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - uses: actions/cache@v3
        id: cache-dist
        with:
          path: ~/code/dist
          key: ${{ github.sha }}

      - name: see version
        run: |
          cat code/dist/version.txt

