name: CI

on:
  push:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache dist
        uses: actions/cache@v3
        env:
          cache-name: cache-dist
        with:
          path: ~/code/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${GITHUB_SHA}

      - name: Save hello
        run: |
          echo "Hello" > hello.txt

   
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Cache dist
        uses: actions/cache@v3
        env:
          cache-name: cache-dist
        with:
          path: ~/code/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${GITHUB_SHA}

      - name: See hello
        run: |
          ls -l


    