name: CI

on:
  push:
    branches:
      - developKILL

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Save hello
        run: |
          echo "Hello" > hello.txt

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

   
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: See hello
        run: |
          ls -l


    